# Generated by Django 4.2.23 on 2025-08-13 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentationSection',
            field=models.CharField(choices=[('PR', 'Project'), ('PL', 'Platform'), ('NE', 'Network'), ('PT', 'Protocols'), ('AP', 'Application'), ('SE', 'Services'), ('SEC', 'Security'), ('DB', 'Databases'), ('TO', 'Tools'), ('DO', 'DevOps'), ('CL', 'Cloud'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('DS', 'Data Science'), ('WD', 'Web Development'), ('MD', 'Mobile Development')], default='PL', max_length=3),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.gitrepository'),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainers', to=settings.AUTH_USER_MODEL),
        ),
    ]
