# Generated by Django 4.2.23 on 2025-08-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documentation',
            name='process_state',
            field=models.CharField(choices=[('DE', 'Development'), ('PR', 'Production')], default='DE', max_length=2),
        ),
        migrations.AddField(
            model_name='documentation',
            name='section',
            field=models.CharField(choices=[('NE', 'Network'), ('PR', 'Protocols'), ('AP', 'Application'), ('SE', 'Services'), ('SEC', 'Security'), ('DB', 'Databases'), ('TO', 'Tools'), ('DO', 'DevOps'), ('CL', 'Cloud'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('DS', 'Data Science'), ('WD', 'Web Development'), ('MD', 'Mobile Development')], default='NE', max_length=3),
        ),
        migrations.AddField(
            model_name='documentation',
            name='doc_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.doctopic'),
        ),
    ]
