# Generated by Django 4.2.23 on 2025-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_doctopic_documentation_process_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='section',
            field=models.CharField(choices=[('PR', 'Project'), ('PL', 'Platform'), ('NE', 'Network'), ('PT', 'Protocols'), ('AP', 'Application'), ('SE', 'Services'), ('SEC', 'Security'), ('DB', 'Databases'), ('TO', 'Tools'), ('DO', 'DevOps'), ('CL', 'Cloud'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('DS', 'Data Science'), ('WD', 'Web Development'), ('MD', 'Mobile Development')], default='NE', max_length=3),
        ),
    ]
